using WTH.Training.Shared;
using WTH.Training.AwardingOrganisations;
using WTH.Training.AwardTypes;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using WTH.Training.Permissions;
using WTH.Training.Awards;

namespace WTH.Training.Awards
{
    public class AwardsAppService : AwardsAppServiceBase, IAwardsAppService
    {
        //<suite-custom-code-autogenerated>
        public AwardsAppService(IAwardRepository awardRepository, AwardManager awardManager, IRepository<WTH.Training.AwardTypes.AwardType, Guid> awardTypeRepository, IRepository<WTH.Training.AwardingOrganisations.AwardingOrganisation, Guid> awardingOrganisationRepository)
            : base(awardRepository, awardManager, awardTypeRepository, awardingOrganisationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}