using Wth.Crm.Employees;
using Wth.Crm.Employees;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.EmployeeEmails
{
    public class EmployeeEmailManager : EmployeeEmailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmployeeEmailManager(IEmployeeEmailRepository employeeEmailRepository)
            : base(employeeEmailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}