using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.EmployeeTelephones;

namespace Wth.Crm.EmployeeTelephones
{
    public class EmployeeTelephonesAppService : EmployeeTelephonesAppServiceBase, IEmployeeTelephonesAppService
    {
        //<suite-custom-code-autogenerated>
        public EmployeeTelephonesAppService(IEmployeeTelephoneRepository employeeTelephoneRepository, EmployeeTelephoneManager employeeTelephoneManager)
            : base(employeeTelephoneRepository, employeeTelephoneManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}