using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using WTH.Training.Permissions;
using WTH.Training.AwardTypes;

namespace WTH.Training.AwardTypes
{
    public class AwardTypesAppService : AwardTypesAppServiceBase, IAwardTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public AwardTypesAppService(IAwardTypeRepository awardTypeRepository, AwardTypeManager awardTypeManager)
            : base(awardTypeRepository, awardTypeManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}