using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.Notes
{
    public class NoteManager : NoteManagerBase
    {
        //<suite-custom-code-autogenerated>
        public NoteManager(INoteRepository noteRepository)
            : base(noteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}