using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.Notes
{
    public class Note : NoteBase
    {
        //<suite-custom-code-autogenerated>
        protected Note()
        {

        }

        public Note(Guid id, string content)
            : base(id, content)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}