using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.CompanyEmails;

namespace Wth.Crm.CompanyEmails
{
    public class CompanyEmailsAppService : CompanyEmailsAppServiceBase, ICompanyEmailsAppService
    {
        //<suite-custom-code-autogenerated>
        public CompanyEmailsAppService(ICompanyEmailRepository companyEmailRepository, CompanyEmailManager companyEmailManager)
            : base(companyEmailRepository, companyEmailManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}