using Wth.Crm.Notes;
using Wth.Crm.Employees;
using Wth.Crm.Employees;
using Wth.Crm.Employees;
using Wth.Crm.Employees;
using Wth.Crm.Employees;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.Employees
{
    public class EmployeeManager : EmployeeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmployeeManager(IEmployeeRepository employeeRepository,
        IRepository<Note, Guid> noteRepository)
            : base(employeeRepository, noteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}