using Wth.Crm.Companies;
using Wth.Crm.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.Employees
{
    public class Employee : EmployeeBase
    {
        //<suite-custom-code-autogenerated>
        protected Employee()
        {

        }

        public Employee(Guid id, Guid? companyId, Guid? employeeId, string firstName, string lastName, EmployeeStatus status, EmployeeType type, string? middleName = null, string? identityNumber = null, string? enrolmentNumber = null, DateOnly? dateOfBirth = null)
            : base(id, companyId, employeeId, firstName, lastName, status, type, middleName, identityNumber, enrolmentNumber, dateOfBirth)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}