using Wth.Crm.Companies;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.CompanyEmails
{
    public class CompanyEmailManager : CompanyEmailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CompanyEmailManager(ICompanyEmailRepository companyEmailRepository)
            : base(companyEmailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}