using Wth.Crm.Companies;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.CompanyEmails
{
    public class CompanyEmail : CompanyEmailBase
    {
        //<suite-custom-code-autogenerated>
        protected CompanyEmail()
        {

        }

        public CompanyEmail(Guid id, Guid companyId, string value, CompanyEmailType type)
            : base(id, companyId, value, type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}