using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace WTH.Training.Awards
{
    public class AwardManager : AwardManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AwardManager(IAwardRepository awardRepository)
            : base(awardRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}