using Wth.Crm.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.EmployeeTelephones
{
    public class EmployeeTelephone : EmployeeTelephoneBase
    {
        //<suite-custom-code-autogenerated>
        protected EmployeeTelephone()
        {

        }

        public EmployeeTelephone(Guid id, Guid employeeId, string value, EmployeeTelephoneType type)
            : base(id, employeeId, value, type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}