using Wth.Crm.Employees;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.EmployeeTelephones
{
    public class EmployeeTelephoneManager : EmployeeTelephoneManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmployeeTelephoneManager(IEmployeeTelephoneRepository employeeTelephoneRepository)
            : base(employeeTelephoneRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}