using Wth.Crm.Notes;
using Wth.Crm.Companies;
using Wth.Crm.Shared;
using Wth.Crm.Addresses;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.Employees;

namespace Wth.Crm.Employees
{
    public class EmployeesAppService : EmployeesAppServiceBase, IEmployeesAppService
    {
        //<suite-custom-code-autogenerated>
        public EmployeesAppService(IEmployeeRepository employeeRepository, EmployeeManager employeeManager, IRepository<Wth.Crm.Companies.Company, Guid> companyRepository, IRepository<Wth.Crm.Notes.Note, Guid> noteRepository)
            : base(employeeRepository, employeeManager, companyRepository, noteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}