using Wth.Crm.Employees;
using Wth.Crm.Addresses;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.EmployeeAddresses
{
    public class EmployeeAddress : EmployeeAddressBase
    {
        //<suite-custom-code-autogenerated>
        protected EmployeeAddress()
        {

        }

        public EmployeeAddress(Guid id, Guid employeeId, Guid addressId, EmployeeAddressType type)
            : base(id, employeeId, addressId, type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}