using Wth.Crm.Employees;
using Wth.Crm.Employees;
using Wth.Crm.Employees;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.EmployeeAddresses
{
    public class EmployeeAddressManager : EmployeeAddressManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmployeeAddressManager(IEmployeeAddressRepository employeeAddressRepository)
            : base(employeeAddressRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}