using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using WTH.Training.Permissions;
using WTH.Training.AwardingOrganisations;

namespace WTH.Training.AwardingOrganisations
{
    public class AwardingOrganisationsAppService : AwardingOrganisationsAppServiceBase, IAwardingOrganisationsAppService
    {
        //<suite-custom-code-autogenerated>
        public AwardingOrganisationsAppService(IAwardingOrganisationRepository awardingOrganisationRepository, AwardingOrganisationManager awardingOrganisationManager)
            : base(awardingOrganisationRepository, awardingOrganisationManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}