using Wth.Crm.Notes;
using Wth.Crm.Shared;
using Wth.Crm.Addresses;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.Companies;

namespace Wth.Crm.Companies
{
    public class CompaniesAppService : CompaniesAppServiceBase, ICompaniesAppService
    {
        //<suite-custom-code-autogenerated>
        public CompaniesAppService(ICompanyRepository companyRepository, CompanyManager companyManager, IRepository<Wth.Crm.Notes.Note, Guid> noteRepository)
            : base(companyRepository, companyManager, noteRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}