using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.EmployeeEmails;

namespace Wth.Crm.EmployeeEmails
{
    public class EmployeeEmailsAppService : EmployeeEmailsAppServiceBase, IEmployeeEmailsAppService
    {
        //<suite-custom-code-autogenerated>
        public EmployeeEmailsAppService(IEmployeeEmailRepository employeeEmailRepository, EmployeeEmailManager employeeEmailManager)
            : base(employeeEmailRepository, employeeEmailManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}