using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.Companies
{
    public class Company : CompanyBase
    {
        //<suite-custom-code-autogenerated>
        protected Company()
        {

        }

        public Company(Guid id, string name, string? taxReference = null)
            : base(id, name, taxReference)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}