using Wth.Crm.Companies;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.CompanyAddresses
{
    public class CompanyAddressManager : CompanyAddressManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CompanyAddressManager(ICompanyAddressRepository companyAddressRepository)
            : base(companyAddressRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}