using Wth.Crm.Companies;
using Wth.Crm.Addresses;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Wth.Crm.CompanyAddresses
{
    public class CompanyAddress : CompanyAddressBase
    {
        //<suite-custom-code-autogenerated>
        protected CompanyAddress()
        {

        }

        public CompanyAddress(Guid id, Guid companyId, Guid addressId, CompanyAddressType type)
            : base(id, companyId, addressId, type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}