using Wth.Crm.Companies;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wth.Crm.CompanyTelephones
{
    public class CompanyTelephoneManager : CompanyTelephoneManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CompanyTelephoneManager(ICompanyTelephoneRepository companyTelephoneRepository)
            : base(companyTelephoneRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}