using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.Notes;

namespace Wth.Crm.Notes
{
    public class NotesAppService : NotesAppServiceBase, INotesAppService
    {
        //<suite-custom-code-autogenerated>
        public NotesAppService(INoteRepository noteRepository, NoteManager noteManager)
            : base(noteRepository, noteManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}