using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace WTH.Training.AwardingOrganisations
{
    public class AwardingOrganisation : AwardingOrganisationBase
    {
        //<suite-custom-code-autogenerated>
        protected AwardingOrganisation()
        {

        }

        public AwardingOrganisation(Guid id, string name, string? email = null, string? telephone = null)
            : base(id, name, email, telephone)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}