using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace WTH.Training.AwardingOrganisations
{
    public class AwardingOrganisationManager : AwardingOrganisationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AwardingOrganisationManager(IAwardingOrganisationRepository awardingOrganisationRepository)
            : base(awardingOrganisationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}