using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Wth.Crm.Permissions;
using Wth.Crm.CompanyTelephones;

namespace Wth.Crm.CompanyTelephones
{
    public class CompanyTelephonesAppService : CompanyTelephonesAppServiceBase, ICompanyTelephonesAppService
    {
        //<suite-custom-code-autogenerated>
        public CompanyTelephonesAppService(ICompanyTelephoneRepository companyTelephoneRepository, CompanyTelephoneManager companyTelephoneManager)
            : base(companyTelephoneRepository, companyTelephoneManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}