using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace WTH.Training.AwardTypes
{
    public class AwardType : AwardTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected AwardType()
        {

        }

        public AwardType(Guid id, string name, bool hasReferenceNumber, bool hasExpiryDate)
            : base(id, name, hasReferenceNumber, hasExpiryDate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}