using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace WTH.Training.AwardTypes
{
    public class AwardTypeManager : AwardTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AwardTypeManager(IAwardTypeRepository awardTypeRepository)
            : base(awardTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}